DROP TABLE IF EXISTS ACCOUNT;

CREATE TABLE ACCOUNT (
  ACCOUNT_ID INT PRIMARY KEY NOT NULL,
  ACC_NUM VARCHAR(100) NOT NULL,
  BALANCE NUMERIC(20, 2)  NOT NULL
);

DROP TABLE IF EXISTS TRANSACTION;

CREATE TABLE TRANSACTION (
  TRANS_ID INT PRIMARY KEY NOT NULL,
  ACC_NUM VARCHAR(100) NOT NULL,
  BALANCE NUMERIC(20, 2)  NOT NULL,
  ACCOUNT_ID INT,
  CONSTRAINT FK_ACCOUNT_ID FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ACCOUNT_ID)

);
